# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import getpass
import os
import sys
import tkinter as tk
from pathlib import Path
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Text, Button, PhotoImage

from src.kindle2pdf import kindle2pdf, OUTPUT_PATH

CURRENT_PATH = Path(os.path.dirname(sys.argv[0]))
ASSETS_PATH = CURRENT_PATH / Path(r"./assets/frame0")


def redirect_stdout_to_text_widget(text_widget):
    class StdoutRedirector:
        def __init__(self, widget):
            self.widget = widget

        def write(self, text):
            self.widget.insert(tk.END, text)
            self.widget.see(tk.END)  # スクロールを最下部に移動する
            self.widget.update_idletasks()  # テキストエリアの再描画
    sys.stdout = StdoutRedirector(text_widget)


def open_kindle_app():
    username = getpass.getuser()
    kindle_path = fr"C:\Users\{username}\AppData\Local\Amazon\Kindle\application\Kindle.exe"
    if os.path.exists(kindle_path):
        os.startfile(kindle_path)
    else:
        print("Kindleアプリが見つかりませんでした。")


def execute():
    clear_text_area(entry_1)
    kindle2pdf()


def open_out_put():
    # resultディレクトリの作成
    if not os.path.exists(OUTPUT_PATH):
        os.makedirs(OUTPUT_PATH)
    os.startfile(OUTPUT_PATH)


def clear_text_area(text_widget):
    text_widget.delete('1.0', tk.END)


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("298x268")
window.geometry("+0+0")
window.configure(bg="#F5F5F5")
window.title("Jisui - kindle2pdf")
window.attributes('-topmost', True)

canvas = Canvas(
    window,
    bg="#F5F5F5",
    height=268,
    width=298,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=open_kindle_app,
    relief="flat"
)
button_1.place(
    x=42.0,
    y=36.0,
    width=62.0,
    height=62.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=open_out_put,
    relief="flat"
)
button_2.place(
    x=207.0,
    y=36.0,
    width=51.0,
    height=62.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=execute,
    relief="flat"
)
button_3.place(
    x=121.0,
    y=37.0,
    width=67.0,
    height=59.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    149.0,
    124.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#F5F5F5",
    fg="#000716",
    highlightthickness=0,
    font=("Inter Bold", 11 * -1)
)
entry_1.place(
    x=41.0,
    y=120.0,
    width=216.0,
    height=125.0
)
redirect_stdout_to_text_widget(entry_1)

canvas.create_text(
    43.0,
    12.0,
    anchor="nw",
    text="Prepare Kindle and press arrow to start.",
    fill="#000000",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    65.0,
    247.0,
    anchor="nw",
    text="kindle2pdf  v1.0.2  Copyright © 2024",
    fill="#000000",
    font=("Inter Bold", 11 * -1)
)
canvas.create_text(
    41.0,
    100.0,
    anchor="nw",
    text="1.Open Kindle",
    fill="#0711FF",
    font=("Inter Bold", 11 * -1)
)

canvas.create_text(
    143.0,
    100.0,
    anchor="nw",
    text="2.Start!",
    fill="#0711FF",
    font=("Inter Bold", 11 * -1)
)

canvas.create_text(
    201.0,
    100.0,
    anchor="nw",
    text="3.Open Folder",
    fill="#0711FF",
    font=("Inter Bold", 11 * -1)
)


def main():
    window.resizable(False, False)
    window.mainloop()


if __name__ == "__main__":
    main()
